from ..domain.Literal import Literal
expression = "(((∃h.C)⊑CO)⊓(OL⊑(∃h.A)⊓(∀h.C))|=(OL(a)⊑CO(a)))"
tokenized_expression = [
    "(", "(", "(", "∃", "h", ".", "C", ")", "⊑", "CO", ")", "⊓", "(", "OL", "⊑", "(", "∃",
    "h", ".", "A", ")", "⊓", "(", "∀", "h", ".", "C", ")", ")", "|=", "(", "OL(a)", "⊑", "CO(a)",
    ")", ")"]
expected_F = [
    Literal("(", 0),
    Literal("(", 1),
    Literal("(", 2),
    Literal("∃", 3),
    Literal("h", 4),
    Literal(".", 5),
    Literal("C", 6),
    Literal(")", 7),
    Literal("⊑", 8),
    Literal("CO", 9),
    Literal(")", 10),
    Literal("⊓", 11),
    Literal("(", 12),
    Literal("OL", 13),
    Literal("⊑", 14),
    Literal("(", 15),
    Literal("∃", 16),
    Literal("h", 17),
    Literal(".", 18),
    Literal("A", 19),
    Literal(")", 20),
    Literal("⊓", 21),
    Literal("(", 22),
    Literal("∀", 23),
    Literal("h", 24),
    Literal(".", 25),
    Literal("C", 26),
    Literal(")", 27),
    Literal(")", 28),
    Literal("|=", 29),
    Literal("(", 30),
    Literal("OL(a)", 31),
    Literal("⊑", 32),
    Literal("CO(a)", 33),
    Literal(")", 34),
    Literal(")", 35),
]
expected_Fin = [
    Literal("(", 0),
    Literal("(", 1),
    Literal("(", 2),
    Literal("h", 4),
    Literal("∃", 3),
    Literal("C", 6),
    Literal(")", 7),
    Literal("⊑", 8),
    Literal("CO", 9),
    Literal(")", 10),
    Literal("⊓", 11),
    Literal("(", 12),
    Literal("OL", 13),
    Literal("⊑", 14),
    Literal("(", 15),
    Literal("h", 17),
    Literal("∃", 16),
    Literal("A", 19),
    Literal(")", 20),
    Literal("⊓", 21),
    Literal("(", 22),
    Literal("h", 24),
    Literal("∀", 23),
    Literal("C", 26),
    Literal(")", 27),
    Literal(")", 28),
    Literal("|=", 29),
    Literal("(", 30),
    Literal("OL(a)", 31),
    Literal("⊑", 32),
    Literal("CO(a)", 33),
    Literal(")", 34),
    Literal(")", 35),
]
