from domain.Literal import Literal
expression = "(((∃h.C)⊑CO)⊓(OL⊑(∃h.A)⊓(∀h.C))|=(OL(a)⊑CO(a)))"
tokenized_expression = [
    "(", "(", "(", "∃", "h", ".", "C", ")", "⊑", "CO", ")", "⊓", "(", "OL", "⊑", "(", "∃",
    "h", ".", "A", ")", "⊓", "(", "∀", "h", ".", "C", ")", ")", "|=", "(", "OL(a)", "⊑", "CO(a)",
    ")", ")"]
expected_F = [
    Literal("(", 0),
    Literal("(", 1),
    Literal("(", 2),
    Literal("∃", 3),
    Literal("h", 4),
    Literal(".", 5),
    Literal("C", 6),
    Literal(")", 7),
    Literal("⊑", 8),
    Literal("CO", 9),
    Literal(")", 10),
    Literal("⊓", 11),
    Literal("(", 12),
    Literal("OL", 13),
    Literal("⊑", 14),
    Literal("(", 15),
    Literal("∃", 16),
    Literal("h", 17),
    Literal(".", 18),
    Literal("A", 19),
    Literal(")", 20),
    Literal("⊓", 21),
    Literal("(", 22),
    Literal("∀", 23),
    Literal("h", 24),
    Literal(".", 25),
    Literal("C", 26),
    Literal(")", 27),
    Literal(")", 28),
    Literal("|=", 29),
    Literal("(", 30),
    Literal("OL(a)", 31),
    Literal("⊑", 32),
    Literal("CO(a)", 33),
    Literal(")", 34),
    Literal(")", 35),
]
expected_Fin = [
    Literal("(", 0),
    Literal("(", 1),
    Literal("(", 2),
    Literal("h", 4),
    Literal("∃", 3),
    Literal("C", 6),
    Literal(")", 7),
    Literal("⊑", 8),
    Literal("CO", 9),
    Literal(")", 10),
    Literal("⊓", 11),
    Literal("(", 12),
    Literal("OL", 13),
    Literal("⊑", 14),
    Literal("(", 15),
    Literal("h", 17),
    Literal("∃", 16),
    Literal("A", 19),
    Literal(")", 20),
    Literal("⊓", 21),
    Literal("(", 22),
    Literal("h", 24),
    Literal("∀", 23),
    Literal("C", 26),
    Literal(")", 27),
    Literal(")", 28),
    Literal("|=", 29),
    Literal("(", 30),
    Literal("OL(a)", 31),
    Literal("⊑", 32),
    Literal("CO(a)", 33),
    Literal(")", 34),
    Literal(")", 35),
]

expected_Fpos = [
    Literal("h", 4),
    Literal("C", 6),
    Literal("∃", 3),
    Literal("CO", 9),
    Literal("⊑", 8),
    Literal("OL", 13),
    Literal("h", 17),
    Literal("A", 19),
    Literal("∃", 16),
    Literal("h", 24),
    Literal("C", 26),
    Literal("∀", 23),
    Literal("⊓", 21),
    Literal("⊑", 14),
    Literal("⊓", 11),
    Literal("OL(a)", 31),
    Literal("CO(a)", 33),
    Literal("⊑", 32),
    Literal("|=", 29),
]

adapted_expression = "((((∃h.C)⊑CO)⊓(OL⊑((∃h.A)⊓(∀h.C))))|=(OL(a)⊑CO(a)))"
adapted_expected_F = [
    Literal("(", 0),
    Literal("(", 1),
    Literal("(", 2),
    Literal("(", 3),
    Literal("∃", 4),
    Literal("h", 5),
    Literal(".", 6),
    Literal("C", 7),
    Literal(")", 8),
    Literal("⊑", 9),
    Literal("CO", 10),
    Literal(")", 11),
    Literal("⊓", 12),
    Literal("(", 13),
    Literal("OL", 14),
    Literal("⊑", 15),
    Literal("(", 16),
    Literal("(", 17),
    Literal("∃", 18),
    Literal("h", 19),
    Literal(".", 20),
    Literal("A", 21),
    Literal(")", 22),
    Literal("⊓", 23),
    Literal("(", 24),
    Literal("∀", 25),
    Literal("h", 26),
    Literal(".", 27),
    Literal("C", 28),
    Literal(")", 29),
    Literal(")", 30),
    Literal(")", 31),
    Literal(")", 32),
    Literal("|=", 33),
    Literal("(", 34),
    Literal("OL(a)", 35),
    Literal("⊑", 36),
    Literal("CO(a)", 37),
    Literal(")", 38),
    Literal(")", 39),
]
adapted_expected_Fin = [
    Literal("(", 0),
    Literal("(", 1),
    Literal("(", 2),
    Literal("(", 3),
    Literal("h", 5),
    Literal("∃", 4),
    Literal("C", 7),
    Literal(")", 8),
    Literal("⊑", 9),
    Literal("CO", 10),
    Literal(")", 11),
    Literal("⊓", 12),
    Literal("(", 13),
    Literal("OL", 14),
    Literal("⊑", 15),
    Literal("(", 16),
    Literal("(", 17),
    Literal("h", 19),
    Literal("∃", 18),
    Literal("A", 21),
    Literal(")", 22),
    Literal("⊓", 23),
    Literal("(", 24),
    Literal("h", 26),
    Literal("∀", 25),
    Literal("C", 28),
    Literal(")", 29),
    Literal(")", 30),
    Literal(")", 31),
    Literal(")", 32),
    Literal("|=", 33),
    Literal("(", 34),
    Literal("OL(a)", 35),
    Literal("⊑", 36),
    Literal("CO(a)", 37),
    Literal(")", 38),
    Literal(")", 39),
]

adapted_expected_Fpos = [
    Literal("h", 5),
    Literal("C", 7),
    Literal("∃", 4),
    Literal("CO", 10),
    Literal("⊑", 9),
    Literal("OL", 14),
    Literal("h", 19),
    Literal("A", 21),
    Literal("∃", 18),
    Literal("h", 26),
    Literal("C", 28),
    Literal("∀", 25),
    Literal("⊓", 23),
    Literal("⊑", 15),
    Literal("⊓", 12),
    Literal("OL(a)", 35),
    Literal("CO(a)", 37),
    Literal("⊑", 36),
    Literal("|=", 33),
]
