from domain.Literal import Literal

expected_fin = [
    Literal("(", 0),
    Literal("(", 1),
    Literal("(", 2),
    Literal("h", 4),
    Literal("∃", 3),
    Literal("C", 6),
    Literal(")", 7),
    Literal("⊑", 8),
    Literal("C", 9),
    Literal("O", 10),
    Literal(")", 11),
    Literal("⊓", 12),
    Literal("(", 13),
    Literal("O", 14),
    Literal("L", 15),
    Literal("⊑", 16),
    Literal("(", 17),
    Literal("h", 19),
    Literal("∃", 18),
    Literal("A", 21),
    Literal(")", 22),
    Literal("⊓", 23),
    Literal("(", 24),
    Literal("h", 26),
    Literal("∀", 25),
    Literal("C", 28),
    Literal(")", 29),
    Literal(")", 30),
    Literal("|", 31),
    Literal("=", 32),
    Literal("(", 33),
    Literal("O", 34),
    Literal("L", 35),
    Literal("(", 36),
    Literal("a", 37),
    Literal(")", 38),
    Literal("⊑", 39),
    Literal("C", 40),
    Literal("O", 41),
    Literal("(", 42),
    Literal("a", 43),
    Literal(")", 44),
    Literal(")", 45),
    Literal(")", 46)
]
